### ISSUE TITLE
컨벤션 제안

### ISSUE THREAD

**Issue by Famec7** [Famec7/OpenSourceProject#2]
## C# 코드 컨벤션
- https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/identifier-names
- 위 사이트 참고하되 public 멤버 변수는 camelCase로 작성 (Property와 구분하기 위함)

## Unity 컨벤션
- Prototype Scene은 Merge할 때 작업할 것이므로 건들지 않기
- 작업마다 Test Scene을 따로 만들어서 작업
- Pull Request에 Merge할 오브젝트 내용 적어두기

## Github 컨벤션
- Commit
   ```
   <type><is breakchange>: <subject> // 제목 Ex.) feat: 자석 아이템 연출 추가
   <BLANK LINE> // 구분줄
   <body>       // 내용  :  무엇을 변경(추가)하였고 왜 변경하였는지 서술
   <BLANK LINE> // EOF
   ```
   - type 종류
      - feat: 기능 (feature)
      - fix: 버그 수정
      - docs: 문서 작업 (documentation)
      - style: 포맷팅, 세미콜론 누락 등.
      - refactor: 리팩터링
      - test: 테스트

- Pull Request
   - Issue와 연동하기
   - 제목은 '[#issue 번호] 변경 사항'로 작성
   - 내용에는 Scene에 무엇이 들어가는지 작성 필수
   - Pull Request 할 때 Code Review 필수
   - Merge 후 branch 삭제

- Issue
  - 오류 뿐만 아니라 Task도 관리
  - 담당자(Assignees) 명시
  - Task List 적극 활용

- Projects
  - 기능 관련 Issue는 Project와 연동
  - Todo, In Progress, Done으로 현황 공유

- branch
  - 무조건 main에서 분기
  - 브랜치명은 feature/구현명으로 명시
  - 자세하게 작성할 것 Ex.) feature/adding-magnet-item

**Comment by Famec7** [comment]
1. Prototype 이후 기능은 변경된 컨벤션 적용
2. 합의 되면 Wiki로 옮길 예정

**Comment by Leekb0804** [comment]
확인했어요
작업할 때 마다 확인할게요

**Comment by JunHyeong777** [comment]
확인했습니다

**Comment by JiHwan-Oh** [comment]
확인했습니다
